
API_ID: '15807865' #https://my.telegram.org/
API_HASH: '1aabd0a02c1662bbaf521a81e782e273'  #https://my.telegram.org/

BOT_TOKEN: '5454701638:AAFd2qRyQRaDoh7PWxXiA2IXc_EKrYDvCJU' #@botfather

STRING_SESSION: '' #python3 session_gen.py

MONGO_URL: ''
MONGO_DB: 'bot' # leave this as it is or change from services/mongo.py this change here. 

REDIS_URI: '127.0.0.1'
REDIS_PORT: 6379
REDIS_PASS: ''

SUPPORT_CHAT: -1001549685862 # send live ccs to here must add bot and make bot admin.
LOG_CHAT: -1001549685862  # send live ccs to here must add bot and make bot admin.
OWNER_ID: 1317173146 #Owner its

ADMINS: 
  - 1317173146


ALLOW_COMMANDS_FROM_EXC: './'
